apiVersion : apps/v1
kind: Deployment
metadata:
  name: sitecontagem 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitecontagem
  template:
    metadata:
      labels:
        app: sitecontagem 
    spec:
      containers:
        - name: sitecontagem 
          image: anpturma3.azurecr.io/sitecontagem
          ports:
          - containerPort: 80